### ISSUE TITLE
No $HOME is set for Administrator

### ISSUE THREAD

**Issue by PoSh82** [jdhitsolutions/ISEScriptingGeek#1]
Hi Jeff
I put in $profile for Admin account your ISEScriptingGeek module.
If I run ISE as Admin, there is no $HOME specified and there is an error message.
I added these 2 lines as a workaround in my $profile for ISE:
Remove-Variable -Force HOME
Set-Variable HOME 'C:\Users\Administrator'

Can you please tell me, why the Admin account has no $HOME specified? 

And can you please update the file ISEScriptingGeek.psm1 with these 2 lines at the top:
if($env:USERNAME -eq 'Administrator')
{ Set-Variable HOME 'C:\Users\Administrator' }

Thx in advance!

Windows 8.1 Pro

$PSVersionTable
Name                                    Value                                                                                                 
----                                        -----                                                                                                 
PSVersion                             4.0                                                                                                   
WSManStackVersion              3.0                                                                                                   
SerializationVersion                1.1.0.1                                                                                               
CLRVersion                           4.0.30319.34209                                                                                       
BuildVersion                           6.3.9600.17400                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                  
PSRemotingProtocolVersion   2.2

**Comment by jdhitsolutions** [comment]
So you are saying you don't have a $home variable or that it has an empty value? Importing the module should have no effect on variables like $Home. If you remove importing the module from the profile and restart the ISE are you still missing the $home variable? Can you test on another machine or with a different account? I can't duplicate this.

**Comment by PoSh82** [comment]
Thx for your quick reply.

My Windows account has no admin rights and I have to enter the local admin credentials in order to start ISE if I want to run it via: Run As Administrator. Then the UAC prompt is asking for Admin credentials.
So ISE starts and then there is an error saying that -Path $HOME is an empty value. and if I look whats $HOME then there is nothing. It's not a bug in your Module, I just don't understand why there is no HOME set up automatically for Admin if I run ISE as Administrator with provided creds. This issue is at my notebook at home and at my work office there's no problem with that. But at my work office I have admin rights on the machine and doesn't need to enter Admin creds if I choose Run As Administrator.

**Comment by jdhitsolutions** [comment]
I see what you are talking about now. After a bit more testing this appears to be a Windows artifact with UAC and PowerShell is simply inheriting it. I logged on as a normal user and opened a CMD prompt. The variables %homedrive% and %homepath% are defined. You can see them by typing the SET command. I then opened a CMD window elevated and these variables are not defined.

I would suggest setting the value of $home in the user profile for the elevated account. Use the CurrentUserAllHosts profile script which will be something like: 

C:\Users\Jeff\Documents\WindowsPowerShell\profile.ps1

Towards the beginning insert this command:
Set-Variable -name HOME -value 'C:\Users\Administrator'  -force

That should fix the problem when starting the ISE.  All that said, I modified the module to use $env:\userprofile instead of $home. They should have the same value and the former is unaffected by UAC.

**Comment by PoSh82** [comment]
Thx. That's great.
